### ISSUE TITLE
Pip-sync Error: When I run pip-sync requirements.txt requirements-dev.txt , I am getting the following error. And instead of installing packages it uninstalls package.

### ISSUE THREAD

**Issue by Haaarrrssshhh** [full-stack-deep-learning/fsdl-text-recognizer-project#21]
Found existing installation: wincertstore 0.2
ERROR: Cannot uninstall 'wincertstore'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Traceback (most recent call last):
  File "c:\users\harsh zota\anaconda3\envs\fsdl-text-recognizer\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\harsh zota\anaconda3\envs\fsdl-text-recognizer\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Harsh Zota\anaconda3\envs\fsdl-text-recognizer\Scripts\pip-sync.exe\__main__.py", line 7, in <module>
  File "C:\Users\Harsh Zota\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Harsh Zota\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Harsh Zota\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Harsh Zota\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\harsh zota\anaconda3\envs\fsdl-text-recognizer\lib\site-packages\piptools\scripts\sync.py", line 153, in cli
    ask=ask,
  File "c:\users\harsh zota\anaconda3\envs\fsdl-text-recognizer\lib\site-packages\piptools\sync.py", line 197, in sync
    + sorted(to_uninstall)
  File "c:\users\harsh zota\anaconda3\envs\fsdl-text-recognizer\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['c:\\users\\harsh zota\\anaconda3\\envs\\fsdl-text-recognizer\\python.exe', '-m', 'pip', 'uninstall', '-y', 'wincertstore']' returned non-zero exit status 1.

**Comment by SasankYadati** [comment]
I tried `pip-sync --user requirements.txt requirements-dev.txt` and it worked. This command will install in the home directory instead of the system directory.

Edit: please don't do this inside a virtual environment.
