### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gitfourteen** [full-stack-deep-learning/fsdl-text-recognizer-project#9]
**### In colab**, _virtual environment_ failed to import **tensroflow**.

Run command as following:

1. `!pwd`
/content/gdrive/My Drive/fsdl-text-recognizer-project/lab2_sln

2. `!nvcc --version`(_for now I have no idea what this info will help debug, just list here FYI_)

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

3. `!pipenv run python` (**failed to import tensorflow!**)
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
 >>>`import tensorflow as tf`

**Traceback (most recent call last):**
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
**ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory**

During handling of the above exception, another exception occurred:

**Traceback (most recent call last):**
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/root/.local/share/virtualenvs/fsdl-text-recognizer-project-iJwlu5A8/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
**ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory**

**Failed to load the native TensorFlow runtime.**

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> ^C

4. `!python` (**this is OK**)
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>` import tensorflow as tf`
>>>` tf.__version__`
'1.14.0'
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> ^C

**Comment by gitfourteen** [comment]
After updating tensorflow to version **1.14.0** in virtual environment, this issue is addressed.

- check outdated package, and find tersorflow '==1.14.0' is available

`!pipenv update --outdated`

- update ONLY tensorflow

`!pipenv update tensorflow`
